version: '3.2'
services:

  #PHP Service
  starbucks_backend-app:
    build:
        context: ../../
        dockerfile: .docker/local/Dockerfile
    image: digitalocean.com/php
    container_name: starbucks_backend-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: starbucks_backend-app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network
    volumes:
       - ../../:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  starbucks_backend-webserver:
    image: nginx:alpine
    container_name: starbucks_backend-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8881:80"
    networks:
      - app-network
    volumes:
      - ../../:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  starbucks_backend-db:
    image: mariadb:10.5.8
    container_name: starbucks_backend-db
    restart: unless-stopped
    tty: true
    ports:
      - "3381:3306"
    environment:
      MYSQL_DATABASE: starbucks_backend
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
